Description: "A simple ASG + Launch Configuration Example"
AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  ParentStack:
    Description: "Stack name of parent VPC stack."
    Type: String

Resources:
  # Datacenter Bind Server Setup
  ASGServerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join ["-", [Ref: "AWS::StackName", "SSMRole"]]
      Path: "/"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
  ASGInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
        - !Ref ASGServerRole

  ASGSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Open-up ports for bind
      GroupName: !Join ["-", [Ref: "AWS::StackName", "ASG-sec-group"]]
      VpcId:
        "Fn::ImportValue": !Sub "NP1-${ParentStack}-VPC"
      SecurityGroupIngress:
        - IpProtocol: icmp
          FromPort: "-1"
          ToPort: "-1"
          CidrIp: 10.0.0.0/8

  LaunchTemplate:
    Type: "AWS::EC2::LaunchTemplate"
    Properties:
      LaunchTemplateName: !Sub "${AWS::StackName}-ASG"
      LaunchTemplateData:
        ImageId: "ami-09693313102a30b2c"
        IamInstanceProfile:
          Name: !Ref ASGInstanceProfile
        InstanceType: "t2.small"
        SecurityGroupIds:
          - Ref: ASGSecGroup

  AutoScalingGroup:
    Type: "AWS::AutoScaling::AutoScalingGroup"
    DependsOn: "LaunchTemplate"
    Properties:
      MinSize: "1"
      MaxSize: "3"
      DesiredCapacity: "1"
      LaunchTemplate:
        LaunchTemplateId:
          Ref: "LaunchTemplate"
        Version:
          Fn::GetAtt: ["LaunchTemplate", "LatestVersionNumber"]
      VPCZoneIdentifier:
        - subnet-0a76c6e989e6384f0
