AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  ParentStack:
    Type: String

  WorkshopName:
    Type: String

  ParentZone:
    Type: String
    Default: aws.seibtribe.com

Resources:
  CDNDNS:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !Join ["", [www, ".", Ref: WorkshopName, ".", Ref: ParentZone, "."]]
      HostedZoneName: !Join ["", [Ref: WorkshopName, ".", Ref: ParentZone, "."]]
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName: !GetAtt [WebsiteCloudfront, DomainName]

  ApexDNS:
    Type: AWS::Route53::RecordSetGroup
    DependsOn:
      - CDNDNS
    Properties:
      HostedZoneName: !Join ["", [Ref: WorkshopName, ".", Ref: ParentZone, "."]]
      RecordSets:
        - Name: !Join ["", [Ref: WorkshopName, ".", Ref: ParentZone, "."]]
          Type: A
          AliasTarget:
            HostedZoneId:
              Fn::ImportValue: !Sub "${ParentStack}-ZoneId"
            DNSName:
              !Join [
                "",
                [www, ".", Ref: WorkshopName, ".", Ref: ParentZone, "."],
              ]

  CloudFrontOriginIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Join ["", ["origin identity for", Ref: WorkshopName]]

  WebsitePolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Fn::ImportValue: !Sub "${ParentStack}-WebBucket"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              CanonicalUser:
                Fn::GetAtt: [CloudFrontOriginIdentity, S3CanonicalUserId]
            Action: "s3:GetObject"
            Resource:
              !Join [
                "",
                ["Fn::ImportValue": !Sub "${ParentStack}-WebARN", "/*"],
              ]

  WebsiteCloudfront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: Cloudfront Distribution pointing to S3 bucket
        Origins:
          - DomainName:
              !Join [
                "",
                [
                  "Fn::ImportValue": !Sub "${ParentStack}-WebBucket",
                  ".s3.amazonaws.com",
                ],
              ]
            Id: webpage
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CloudFrontOriginIdentity}"
        Enabled: true
        HttpVersion: "http2"
        DefaultRootObject: index.html
        Aliases:
          - !Join [".", [www, Ref: WorkshopName, Ref: ParentZone]]
          - !Join [".", [Ref: WorkshopName, Ref: ParentZone]]
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          Compress: true
          DefaultTTL: 60
          TargetOriginId: webpage
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
        PriceClass: PriceClass_100
        ViewerCertificate:
          AcmCertificateArn:
            Fn::ImportValue: !Sub "${ParentStack}-ACMArn"
          SslSupportMethod: sni-only
